name: Selenium Cucumber CI Pipeline

on:
  push:
    branches:
      - Dev   # Trigger pipeline when code is pushed to Dev branch
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17 (you can change this if you use another version)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Step 4: Build project and run tests
      - name: Run Automation Tests
        run: mvn clean test

      # Step 5: Upload test reports (Extent, HTML, or Cucumber)
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/cucumber-reports/
            target/ExtentReports/
            target/surefire-reports/
